// app/layout.tsx or app/layout.ts
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/app/components/Header/Header";
import { Footer } from "@/app/components/Footer";
import { UIProvider } from "@/providers/ui-context";
import { fetchSinglePartnerniva } from "@/lib/apollo/fetchPartnernivaer/fetchSinglePartnernivaAction";
import PartnerHeader from "./components/Partners/PartnerHeader";
import { AdminBar } from "./components/AdminBar/index";
import { draftMode } from 'next/headers';
import { getTopbarConfig } from "@/lib/leagueCache";
import Script from "next/script";
import { fetchFooter } from "@/lib/frontspace/client";

const oswald = localFont({
  src: [
    { path: "fonts/oswald-v53-latin-regular.woff2", weight: "400", style: "normal" },
    { path: "fonts/oswald-v53-latin-regular.woff", weight: "400", style: "normal" },
    { path: "fonts/oswald-v53-latin-regular.ttf", weight: "400", style: "normal" },
    { path: "fonts/oswald-v53-latin-700.woff2", weight: "700", style: "bold" },
    { path: "fonts/oswald-v53-latin-700.woff", weight: "700", style: "bold" },
    { path: "fonts/oswald-v53-latin-700.ttf", weight: "700", style: "bold" },
  ],
  variable: "--font-oswald",
});

const poppins = localFont({
  src: [
    // 300 - Light
    { path: "fonts/poppins-v23-latin-300.woff2", weight: "300", style: "normal" },
    { path: "fonts/poppins-v23-latin-300.woff", weight: "300", style: "normal" },
    { path: "fonts/poppins-v23-latin-300.ttf", weight: "300", style: "normal" },

    // 400 - Regular
    { path: "fonts/poppins-v23-latin-regular.woff2", weight: "400", style: "normal" },
    { path: "fonts/poppins-v23-latin-regular.woff", weight: "400", style: "normal" },
    { path: "fonts/poppins-v23-latin-regular.ttf", weight: "400", style: "normal" },

    // 700 - Bold
    { path: "fonts/poppins-v23-latin-700.woff2", weight: "700", style: "normal" },
    { path: "fonts/poppins-v23-latin-700.woff", weight: "700", style: "normal" },
    { path: "fonts/poppins-v23-latin-700.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Östers IF",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Get topbar configuration based on current season
  const topbarConfig = await getTopbarConfig();

  // Fetch footer from Frontspace CMS
  const footer = await fetchFooter();

  return (
    <html lang="sv">
      <head>
        <meta name="robots" content="index" />
        {/* SEF/EFD Top Bar Widget Script */}
        <Script
          id="league-top-bar-script"
          src="https://topbar.svenskelitfotboll.se/top-bar-script.min.js"
          strategy="afterInteractive"
          data-allsvenskan={topbarConfig.allsvenskan.toString()}
          data-superettan={topbarConfig.superettan.toString()}
          data-damallsvenskan={topbarConfig.damallsvenskan.toString()}
          data-elitettan={topbarConfig.elitettan.toString()}
        />
      </head>
      <body className={`${oswald.variable} ${poppins.variable} antialiased bg-custom_dark_dark_red`}>
        <UIProvider>
          <div className="sef-topbar-widget"></div>
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          {footer && <Footer footer={footer} />}
        </UIProvider>
      </body>
    </html>
  );
}
